### ISSUE TITLE
I can not run the code based on your README

### ISSUE THREAD

**Issue by hunzhizi** [llnl/HPAC#2]
I haven't familiarized myself with HPAC, but I strictly followed the instructions in the HPAC-offload's README document for configuration. However, I found that the current version of CMake doesn't support compilation. After upgrading CMake and executing setup.py, when I run ./examples/lulesh.sh 'size' 'visualize', I encounter a FileNotFoundError: [Errno 2] No such file or directory: 'build/lulesh.yaml'. Could you please help me understand why this error occurs?

**Comment by koparasy** [comment]
@ZwFink can you help here?

**Comment by ZwFink** [comment]
Yes! I'm not familiar with the issue. I'll follow up on Monday

**Comment by ZwFink** [comment]
Can you paste the full output of the HPAC build script? Also, which version of HPAC are you trying to build? CPU or HPAC-Offload?

**Comment by hunzhizi** [comment]
> Can you paste the full output of the HPAC build script? Also, which version of HPAC are you trying to build? CPU or HPAC-Offload?
I want to build HPAC-Offload.

I started the docker with command:
` sudo docker container run --gpus all -itd -v /home/ps/zhouenyu_workspace/HPAC:/HPAC  --name DontRmMyHPAC-offload  -e NVIDIA_DRIVER_CAPABILITIES=compute,utility -e NVIDIA_VISIBLE_DEVICES=all  nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04 /bin/bash` to ensure I could use gpus.
Currently,the dependencies in my docker are:
Ninja 1.10.0
CMAKE 3.27.7
gcc 9.4.0
python 3.8.10
pandas 1.2.2
numpy 1.20.1
matplotlib 3.3.4
seaborn 0.11.1
pyyaml 5.4.1

I followed the instructions in the HPAC-offload's README document [the script I ran](https://github.com/LLNL/HPAC/tree/hpac_offload#build-hpac)
I was using this command: root@cae7e8de60f9:/HPAC/HPAC-hpac_offload# ./setup.sh /HPAC/HPAC-hpac_offload/bin_exe 20 >> setup.log
The following information is directly output to the terminal, and I upload setup.log as an attachment:
CMake Deprecation Warning at /HPAC/HPAC-hpac_offload/cmake/Modules/CMakePolicy.cmake:6 (cmake_policy):
  The OLD behavior for policy CMP0114 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:13 (include)


CMake Warning at cmake/modules/VersionFromVCS.cmake:49 (message):
  Git not found.  Version cannot be determined.
Call Stack (most recent call first):
  CMakeLists.txt:1037 (get_source_info)


CMake Deprecation Warning at /HPAC/HPAC-hpac_offload/cmake/Modules/CMakePolicy.cmake:6 (cmake_policy):
  The OLD behavior for policy CMP0114 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  /HPAC/HPAC-hpac_offload/clang/CMakeLists.txt:6 (include)


CMake Warning (dev) at /HPAC/HPAC-hpac_offload/clang/tools/nvptx-arch/CMakeLists.txt:13 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning:
  Manually-specified variables were not used by the project:

    Python3_EXECUTEABLE


CMake Warning (dev) at /HPAC/HPAC-hpac_offload/openmp/libomptarget/cmake/Modules/LibomptargetGetDependencies.cmake:107 (find_package):  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

Call Stack (most recent call first):
  /HPAC/HPAC-hpac_offload/openmp/libomptarget/CMakeLists.txt:31 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

Failed to 'dlopen' libhsa-runtime64.so
CMake Warning:
  Manually-specified variables were not used by the project:

    COMPILER_RT_BUILD_BUILTINS
    LLVM_CONFIG_PATH
    LLVM_ENABLE_PER_TARGET_RUNTIME_DIR
    LLVM_ENABLE_PROJECTS_USED


CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

Targeting nvptx64 with compute capability: sm_86
LINKER FLAGS ARE 
libapprox is /HPAC/HPAC-hpac_offload/approx/runtime/src/include
libapprox is /HPAC/HPAC-hpac_offload/clang//include/
approx include is /HPAC/HPAC-hpac_offload/approx/runtime/src/include
PACKAGE VERSION is: 16
[setup.log](https://github.com/LLNL/HPAC/files/13277242/setup.log)

when I executed the setup.py , I directly ran [./examples/lavaMD.sh 'size' 0](https://github.com/LLNL/HPAC/tree/hpac_offload#replicate-analysis-of-sc-21) trying to replicate the experiment, but the output told me that the program lacks some '.yml' files. Here are the info:
Traceback (most recent call last):
  File "./benchmark.py", line 577, in <module>
    main()
  File "./benchmark.py", line 463, in main
    with open(args.input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build/lulesh.yaml'
Traceback (most recent call last):
  File "./benchmark.py", line 577, in <module>
    main()
  File "./benchmark.py", line 463, in main
    with open(args.input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build/lulesh.yaml'
Traceback (most recent call last):
  File "./benchmark.py", line 577, in <module>
    main()
  File "./benchmark.py", line 463, in main
    with open(args.input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build/lulesh.yaml'
Traceback (most recent call last):
  File "./benchmark.py", line 577, in <module>
    main()
  File "./benchmark.py", line 463, in main
    with open(args.input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build/lulesh.yaml'
Traceback (most recent call last):
  File "./benchmark.py", line 577, in <module>
    main()
  File "./benchmark.py", line 463, in main
    with open(args.input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build/lulesh.yaml'
Traceback (most recent call last):
  File "./benchmark.py", line 577, in <module>
    main()
  File "./benchmark.py", line 463, in main
    with open(args.input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build/lulesh.yaml'
Traceback (most recent call last):
  File "./benchmark.py", line 577, in <module>
    main()
  File "./benchmark.py", line 463, in main
    with open(args.input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build/lulesh.yaml'
Traceback (most recent call last):
  File "./benchmark.py", line 577, in <module>
    main()
  File "./benchmark.py", line 463, in main
    with open(args.input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build/lulesh.yaml'
Traceback (most recent call last):
  File "./benchmark.py", line 577, in <module>
    main()
  File "./benchmark.py", line 463, in main
    with open(args.input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build/lulesh.yaml'
Traceback (most recent call last):
  File "./benchmark.py", line 577, in <module>
    main()
  File "./benchmark.py", line 463, in main
    with open(args.input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build/lulesh.yaml'
Traceback (most recent call last):
  File "./benchmark.py", line 577, in <module>
    main()
  File "./benchmark.py", line 463, in main
    with open(args.input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build/lulesh.yaml'
Traceback (most recent call last):
  File "./benchmark.py", line 577, in <module>
    main()
  File "./benchmark.py", line 463, in main
    with open(args.input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build/lulesh.yaml'
Traceback (most recent call last):
  File "./benchmark.py", line 577, in <module>
    main()
  File "./benchmark.py", line 463, in main
    with open(args.input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build/lulesh.yaml'
Traceback (most recent call last):
  File "./benchmark.py", line 577, in <module>
    main()
  File "./benchmark.py", line 463, in main
    with open(args.input, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'build/lulesh.yaml'
Traceback (most recent call last):
  File "analysis_scripts/concatenate.py", line 95, in <module>
    df = pd.concat(processed_final)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/concat.py", line 285, in concat
    op = _Concatenator(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/concat.py", line 342, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
Traceback (most recent call last):
  File "analysis_scripts/viz_lulesh.py", line 306, in <module>
    df = pd.read_pickle(input_file)
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/pickle.py", line 185, in read_pickle
    with get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 651, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'analysis_results/lulesh.pkl'

**Comment by ZwFink** [comment]
Aha, I see. You are building HPAC-Offload, correct? I apologize that there is a documentation deficiency: I need to update the README on that branch to reflect the build procedure. You have successfully built the compiler, but we use a different execution harness for this version. It can be found here: https://github.com/zwfink/hpac_offload_artifact

I apologize for the confusion. We are working to improve the documentation and workflow.

**Comment by hunzhizi** [comment]
> Aha, I see. You are building HPAC-Offload, correct? I apologize that there is a documentation deficiency: I need to update the README on that branch to reflect the build procedure. You have successfully built the compiler, but we use a different execution harness for this version. It can be found here: https://github.com/zwfink/hpac_offload_artifact
> 
> I apologize for the confusion. We are working to improve the documentation and workflow.

Thank you for the clarification and providing the updated information. I appreciate your efforts to improve the documentation and workflow. I will have a try on hpac_offload_artifact. If you have any update about this project, please let me know. Thank you for your contribution.
