### ISSUE TITLE
I don't understand why did you have a 'exit' in your setup.py 

### ISSUE THREAD

**Issue by hunzhizi** [llnl/HPAC#3]
This is my first to execute the code, I never used HPAC . When I execute setup.py , I was wondering if the exit would affect the result?

**Comment by koparasy** [comment]
Can you elaborate? On which exit are you referring to?

**Comment by hunzhizi** [comment]
> Can you elaborate? On which exit are you referring to?

Thanks for replying. 
![image](https://github.com/LLNL/HPAC/assets/57383237/cb17fa2e-bbc8-4810-9eec-a035b1d4e3c6)
line 97
And also , in line 27, "approx_runtime_lib=/dev/null" this is also different from the HPAC's setup.py . I don't konw why this variable is "/dev/null"
